spring:
  application:
    name: spring-ai-openrouter-example

  config:
    import: "${SPRING_CONFIG_IMPORT:optional:file:./config/creds.yml}"

  ai:
    model:
      chat: openai
    openrouter:
      chat:
        options:
          models:
            - qwen/qwen3.7-max
            - ~anthropic/claude-haiku-latest
            - meta-llama/llama-3.3-70b-instruct
            - deepseek/deepseek-chat
            - openai/gpt-4o-2024-11-20
            - amazon/nova-pro-v1
            - ~google/gemini-flash-latest
            - mistralai/ministral-3b-2512

    openai:
      base-url: ${OPENAI_BASE_URL:https://openrouter.ai/api/v1}
      chat:
        options:
          model: ${CHAT_MODEL:deepseek/deepseek-chat}

  threads:
    virtual:
      enabled: true

management:
  info:
    build:
      enabled: true
    git:
      mode: FULL
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers,sbom

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  packagesToScan: me.pacphi.controller
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  writer-with-default-pretty-printer: true

---

spring:
  config:
    activate:
      on-profile: dev

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    me.pacphi: TRACE
    org.springframework: DEBUG
