spring:
  application:
    name: spring-ai-openrouter-example

  config:
    import: "${SPRING_CONFIG_IMPORT:optional:file:./config/creds.yml}"

  ai:
    openrouter:
      chat:
        options:
          models:
            - google/gemini-2.0-flash-exp:free
            - meta-llama/llama-3.3-70b-instruct
            - deepseek/deepseek-chat
            - qwen/qvq-72b-preview
            - openai/gpt-4o-2024-11-20
            - amazon/nova-pro-v1
            - mistralai/mistral-large-2411
            - anthropic/claude-3.5-haiku-20241022
            - perplexity/llama-3.1-sonar-huge-128k-online
            - pygmalionai/mythalion-13b
            - anthracite-org/magnum-v2-72b
            - x-ai/grok-2-1212

    openai:
      base_url: ${OPENAI_BASE_URL:https://openrouter.ai/api}
      chat:
        options:
          model: ${CHAT_MODEL:deepseek/deepseek-chat}

  threads:
    virtual:
      enabled: true

management:
  info:
    build:
      enabled: true
    git:
      mode: FULL
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers,sbom

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  packagesToScan: me.pacphi.controller
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  writer-with-default-pretty-printer: true

---

spring:
  config:
    activate:
      on-profile: dev

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    me.pacphi: TRACE
    org.springframework: DEBUG
